//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringCompareClient.IISService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISService.IStringCount")]
    public interface IStringCount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCount/GetSubstringCount", ReplyAction="http://tempuri.org/IStringCount/GetSubstringCountResponse")]
        int GetSubstringCount(string input, string substring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCount/GetSubstringCount", ReplyAction="http://tempuri.org/IStringCount/GetSubstringCountResponse")]
        System.Threading.Tasks.Task<int> GetSubstringCountAsync(string input, string substring);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringCountChannel : StringCompareClient.IISService.IStringCount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringCountClient : System.ServiceModel.ClientBase<StringCompareClient.IISService.IStringCount>, StringCompareClient.IISService.IStringCount {
        
        public StringCountClient() {
        }
        
        public StringCountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringCountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSubstringCount(string input, string substring) {
            return base.Channel.GetSubstringCount(input, substring);
        }
        
        public System.Threading.Tasks.Task<int> GetSubstringCountAsync(string input, string substring) {
            return base.Channel.GetSubstringCountAsync(input, substring);
        }
    }
}
